---

  - name: TRUECRYPT | Add ppa repositories
    apt_repository: repo='ppa:stefansundin/truecrypt' state=present
    become: yes

  - name: TRUECRYPT | Install package
    apt: pkg="truecrypt" update_cache="yes"
    become: yes
